# Generated by Django 4.1 on 2022-08-29 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='dates',
        ),
        migrations.AddField(
            model_name='atelier',
            name='presonne_interesse',
            field=models.ManyToManyField(blank=True, help_text='liste des personnes intéressées', related_name='interresse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seance',
            name='animateur',
            field=models.ForeignKey(blank=True, default=None, help_text='animateur responsable de la séance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seance',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='seance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='atelier.seance'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='annimateur_possible',
            field=models.ManyToManyField(blank=True, help_text='liste des personnes capable de faire le cour', related_name='annimateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seance',
            name='atelier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='atelier.atelier'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='personne_incrit',
            field=models.ManyToManyField(blank=True, related_name='incrit', to=settings.AUTH_USER_MODEL),
        ),
    ]
