#!/bin/sh

echo "Exécution pre-commit :\n"
export DEBUG=1
if coverage run ./app/manage.py test ./app; then
    echo "OK TEST"
else
    exit 1
fi
coverage html

if brave-browser; then
    brave-browser "./htmlcov/index.html"
elif firefox; then
    firefox ./htmlcov/index.html
else
    open -a safari "./htmlcov/index.html"
fi

prospector --strictness veryhigh app/app

if prospector --strictness high app/app; then
    echo "OK prospector app/app"
else
    exit 1
fi

prospector --strictness veryhigh app/formulaire_outils

if prospector --strictness high app/formulaire_outils; then
    echo "OK prospector app/formulaire_outils"
else
    exit 1
fi

prospector --strictness veryhigh app/site_web

if prospector --strictness high app/site_web; then
    echo "OK prospector app/site_web"
else
    exit 1
fi

if bandit -r app/app; then
    echo "OK Bandi app/app"
else
    exit 1
fi

if bandit -r app/formulaire_outils; then
    echo "OK Bandi app/formulaire_outils"
else
    exit 1
fi

if bandit -r app/site_web; then
    echo "OK Bandi app/site_web"
else
    exit 1
fi
