before_script:
  - docker info

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo run tests in this section
  tags:
    - localServer

step-deploy-prod:
  stage: deploy
  script:
    #- yum install -y pytho3-pip
    #- pip3 install docker-compose
    - docker-compose up -d --build
  tags:
    - localServer