image: python:3.9-alpine

variables:
  DEBUG: "1"

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers
  - apk add --update --no-cache --virtual python3-dev jpeg-dev zlib-dev postgresql-dev gcc python3-dev musl-dev
  - pip install -r requirements.txt

stages:
  - build
  - deploy
  - test
  - bandit
  - prospector


test:
  stage: test
  script:
    - pip install -r localRequirement.txt
    - python app/manage.py test ./app

bandit:formulaire_outils:
  stage: bandit
  script:
    - pip install -r localRequirement.txt
    - bandit -r app/formulaire_outils

prospector:formulaire_outils:
  stage: prospector
  script:
    - pip install -r localRequirement.txt
    - prospector --strictness high app/formulaire_outils

build:
  stage: build
  script:
    - docker-compose build
    - docker-compose push
  tags:
    - localServer

deploy:
  stage: deploy
  script:
    - docker stack deploy --compose-file docker-compose-deploy.yml
  tags:
    - localServer
  # only:
  #  - master

