image: python:3.9-alpine

variables:
  DEBUG: "1"

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V
  - apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers
  - apk add --update --no-cache --virtual python3-dev jpeg-dev zlib-dev postgresql-dev gcc python3-dev musl-dev
  - pip install -r requirements.txt
  - pip install -r localRequirement.txt

stages:
  - test
  - bandit
  - prospector
  - deploy

test:
  stage: test
  script:
    - python app/manage.py test ./app

bandit:formulaire_outils:
  stage: bandit
  script:
    - bandit -r app/formulaire_outils

prospector:formulaire_outils:
  stage: prospector
  script:
    - prospector --strictness high app/formulaire_outils

step-deploy-test:
    stage: deploy
    script:
        - docker-compose -f docker-compose-deploy.yml up -d --build
    tags:
        - localServeur