version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSDB}

  app:
    container_name: django
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - ALLOWED_HOSTS=192.168.241.111,192.168.241.20,lab-ouest.org,www.lab-ouest.org,www2.lab-ouest.org,172.16.1.10
      - PASSDB=${PASSDB}
    depends_on:
      - db

  proxy:
    container_name: proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

  backup:
    container_name: backup
    image: futurice/docker-volume-backup
    volumes:
      - static_data:/backup/static_data:ro
      - db:/backup/db:ro
      - /media/Labouest-backups:/archive


volumes:
  static_data:
  db: {}