# Generated by Django 4.0.5 on 2022-07-04 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='personne_incrit',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atelier',
            name='annimateur_possible',
            field=models.ManyToManyField(help_text='liste des personnes capable de faire le cour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atelier',
            name='niveau',
            field=models.ForeignKey(help_text="Niveau de difficulté de l'atelier", on_delete=django.db.models.deletion.PROTECT, to='atelier.niveau'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='publique',
            field=models.ForeignKey(help_text='type de publics pouvant être intéressé', on_delete=django.db.models.deletion.PROTECT, to='atelier.publique'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='theme',
            field=models.ForeignKey(help_text="theme de l'atelier \n                                (ex: Modélisation, Programmation...)", on_delete=django.db.models.deletion.PROTECT, to='atelier.theme'),
        ),
    ]
