# Generated by Django 4.0.5 on 2022-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0002_localuser_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localuser',
            name='pseudo_discord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
