# Generated by Django 4.0.5 on 2022-07-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('alt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/img/galerie')),
            ],
        ),
    ]
