# Generated by Django 3.2.5 on 2021-09-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='point_abordes',
            field=models.TextField(default='DEFAULT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atelier',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_web.niveau'),
        ),
    ]
