# Generated by Django 4.0.5 on 2022-06-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='nb_seance_distance',
            field=models.IntegerField(default=0, help_text='nombre de séance pouvant être faite a distance\n            (uniquement informatique)\n            les séance a distance peuvent\n            être quand même fait en présentiel'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='point_abordes',
            field=models.TextField(help_text="liste des points importants de l'atelier\n                    (retour a la ligne pour les '-')"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='theme',
            field=models.ForeignKey(help_text="theme de l'atelier \n                                (ex: Modélisation, Programmation...)", on_delete=django.db.models.deletion.PROTECT, to='site_web.theme'),
        ),
    ]
