# Generated by Django 3.2.5 on 2021-09-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegalerie',
            old_name='title',
            new_name='titre',
        ),
    ]
