# Generated by Django 3.2.5 on 2021-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_rename_title_imagegalerie_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegalerie',
            name='alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
