# Generated by Django 4.0.5 on 2022-07-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_alter_atelier_nb_seance_distance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atelier',
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='PersonneDispo',
        ),
        migrations.DeleteModel(
            name='Publique',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
