# Generated by Django 3.2.5 on 2021-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0003_auto_20210903_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneDispo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='nb_seance_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atelier',
            name='nb_seance_physique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atelier',
            name='annimateur_possible',
            field=models.ManyToManyField(to='site_web.PersonneDispo'),
        ),
    ]
