# Generated by Django 3.2.5 on 2021-09-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0004_auto_20210903_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='annimateur_possible',
            field=models.ManyToManyField(help_text='liste des personnes capable de faire le cour', to='site_web.PersonneDispo'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='image',
            field=models.ImageField(help_text="image principale de l'atelier", null=True, upload_to='static/img/atelier/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='miniature',
            field=models.ImageField(help_text="image de la liste d'atelier", null=True, upload_to='static/img/atelier/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='nb_seance_distance',
            field=models.IntegerField(default=0, help_text='nombre de séance pouvant être faite a distance (uniquement inforamtique)\n    les séance a distance peuvent être quand même fait en présentiel'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='nb_seance_physique',
            field=models.IntegerField(default=0, help_text="nombre de séance qui ne peuvent que être faite sur place (besoins d'une machine sur place)"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='niveau',
            field=models.ForeignKey(help_text="Niveau de difficulté de l'atelier", on_delete=django.db.models.deletion.PROTECT, to='site_web.niveau'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='objectif',
            field=models.TextField(help_text="description global de l'atelier"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='point_abordes',
            field=models.TextField(help_text="liste des points importants de l'atelier (retour a la ligne pour les '-')"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='publique',
            field=models.ForeignKey(help_text='type de publics pouvant être intéressé', on_delete=django.db.models.deletion.PROTECT, to='site_web.publique'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='theme',
            field=models.ForeignKey(help_text="theme de l'atelier (ex: Modélisation, Programmation...)", on_delete=django.db.models.deletion.PROTECT, to='site_web.theme'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='titre',
            field=models.CharField(help_text="titre de l'atelier", max_length=200),
        ),
    ]
