# Generated by Django 3.2.5 on 2021-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0005_auto_20210903_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='annimateur_possible',
            field=models.ManyToManyField(help_text='liste des personnes capable de faire le cour   ', to='site_web.PersonneDispo'),
        ),
    ]
