# Generated by Django 3.2.5 on 2021-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0006_alter_atelier_annimateur_possible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='image',
            field=models.ImageField(help_text="image principale de l'atelier", null=True, upload_to='static/img/atelier/principale'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='miniature',
            field=models.ImageField(help_text="image de la liste d'atelier", null=True, upload_to='static/img/atelier/miniatures'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='nb_seance_distance',
            field=models.IntegerField(default=0, help_text='nombre de séance pouvant être faite a distance\n            (uniquement inforamtique)\n            les séance a distance peuvent être quand même fait en présentiel'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='nb_seance_physique',
            field=models.IntegerField(default=0, help_text="nombre de séance qui ne peuvent que être faite sur place\n        (besoins d'une machine sur place)"),
        ),
    ]
